### ISSUE TITLE
Attempted to load class "Twig_Function_Method" from the global namespace.

### ISSUE THREAD

**Issue by emulienfou** [symfony-cmf/CreateBundle#166]
Hi!

I've got the error: **Attempted to load class "Twig_Function_Method" from the global namespace.** after installing the package from **2.0.x-dev** branch!

After investigation, I found that this package require **midgard/createphp** from `^1.1` branch.
However, to avoid this error, you need to require **midgard/createphp** from branch `dev-master`.

Hope this will help and can be fixed!

**Comment by dbu** [comment]
yeah, i think twig has moved to namespaces since quite a while.

note that we do not maintain the CreateBundle anymore, due to lacking resources. midgard/createphp would also need quite an effort to bring up to date again. as does the create.js library. its a cool tool chain, but personally i don't need it at work anymore and its too much effort to do just for fun... looks like its similar for the other cmf contributors.

**Comment by emulienfou** [comment]
Yes you're right, closing this issue!
